apiVersion: apps/v1
kind: Deployment
metadata:
  name: koajs-deployment
  labels:
    app: koajs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: koajs-app
  template:
    metadata:
      labels:
        app: koajs-app
    spec:
      containers:
      - name: koajs-app
        image: koajsapp:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 3000
